parameters:
    darvin_admin.ace_editor.form_type.class: Darvin\AdminBundle\Form\Type\AceEditorType

services:
    _defaults:
        public: true

    darvin_admin.ace_editor.form_type:
        class: "%darvin_admin.ace_editor.form_type.class%"
        arguments:
            -
                minLines: 15
                maxLines: 15
                theme:    ace/theme/github
            -
                margin: 0 20px
        tags:
            - { name: form.type }
