parameters:
    darvin_admin.asset.dumper.generic.class: Darvin\AdminBundle\Asset\Dumper\GenericAssetsDumper

    darvin_admin.asset.dumper.styles.destination: Resources/public/styles/prod/app.css

    darvin_admin.asset.provider.generic.class:   Darvin\AdminBundle\Asset\Provider\GenericAssetsProvider
    darvin_admin.asset.provider.generic.web_dir: %kernel.root_dir%/../web

    darvin_admin.asset.provider.styles.web_pathnames:
        - bundles/darvinadmin/styles/bootstrap.css
        - bundles/darvinadmin/styles/bootstrap-chosen.css
        - bundles/darvinadmin/styles/jquery-jscrollpane.css
        - bundles/darvinadmin/styles/jquery-ui.css
        - bundles/darvinadmin/styles/jquery-ui-timepicker-addon.css
        - bundles/darvinadmin/styles/dropzone.css
        - bundles/darvinadmin/styles/fancybox.css
        - bundles/a2lixtranslationform/css/a2lix_translation_default.css

services:
    darvin_admin.asset.dumper.styles:
        class: %darvin_admin.asset.dumper.generic.class%
        arguments:
            - "@darvin_admin.asset.provider.styles"
            - "@kernel"
            - %darvin_admin.asset.dumper.styles.destination%
        calls:
            - [ addFilter, [ "@assetic.filter.cssembed" ] ]
            - [ addFilter, [ "@assetic.filter.cssrewrite" ] ]
            - [ addFilter, [ "@assetic.filter.yui_css" ] ]

    darvin_admin.asset.provider.styles:
        class: %darvin_admin.asset.provider.generic.class%
        arguments:
            - %darvin_admin.asset.provider.generic.web_dir%
            - %darvin_admin.asset.provider.styles.web_pathnames%
