parameters:
    darvin_admin.asset.compiler.pool.class: Darvin\AdminBundle\Asset\Compiler\AssetCompilerPool

    darvin_admin.asset.compiler.generic.class: Darvin\AdminBundle\Asset\Compiler\GenericAssetCompiler

    darvin_admin.asset.provider.pool.class: Darvin\AdminBundle\Asset\Provider\AssetProviderPool

    darvin_admin.asset.provider.generic.class:   Darvin\AdminBundle\Asset\Provider\GenericAssetProvider
    darvin_admin.asset.provider.generic.web_dir: %kernel.root_dir%/../web

    darvin_admin.asset.provider.styles.compiled_asset_pathname: styles/prod/app.css
    darvin_admin.asset.provider.styles.dev_asset_web_pathnames:
        - bundles/darvinadmin/styles/bootstrap.css
        - bundles/darvinadmin/styles/bootstrap-chosen.css
        - bundles/darvinadmin/styles/jquery-jscrollpane.css
        - bundles/darvinadmin/styles/jquery-ui.css
        - bundles/darvinadmin/styles/jquery-ui-timepicker-addon.css
        - bundles/darvinadmin/styles/dropzone.css
        - bundles/darvinadmin/styles/fancybox.css
        - bundles/a2lixtranslationform/css/a2lix_translation_default.css

services:
    darvin_admin.asset.compiler.pool:
        class: %darvin_admin.asset.compiler.pool.class%

    darvin_admin.asset.compiler.styles:
        class:  %darvin_admin.asset.compiler.generic.class%
        public: false
        arguments:
            - "@darvin_admin.asset.provider.styles"
        calls:
            - [ addFilter, [ "@assetic.filter.cssembed" ] ]
            - [ addFilter, [ "@assetic.filter.cssrewrite" ] ]
            - [ addFilter, [ "@assetic.filter.yui_css" ] ]
        tags:
            - { name: darvin_admin.asset_compiler }

    darvin_admin.asset.provider.pool:
        class:  %darvin_admin.asset.provider.pool.class%
        public: false

    darvin_admin.asset.provider.styles:
        class:  %darvin_admin.asset.provider.generic.class%
        public: false
        arguments:
            - "@kernel"
            - %darvin_admin.asset.provider.generic.web_dir%
            - %darvin_admin.asset.provider.styles.dev_asset_web_pathnames%
            - %darvin_admin.asset.provider.styles.compiled_asset_pathname%
        tags:
            - { name: darvin_admin.asset_provider, alias: styles }
