parameters:
    darvin_admin.breadcrumbs.twig_extension.class: Darvin\AdminBundle\Twig\Extension\BreadcrumbsExtension

services:
    _defaults:
        public: true

    darvin_admin.breadcrumbs.twig_extension:
        class:  '%darvin_admin.breadcrumbs.twig_extension.class%'
        public: false
        arguments:
            - '@darvin_admin.router'
            - '@router'
            - '@darvin_admin.metadata.identifier_accessor'
            - '@darvin_admin.metadata.manager'
            - '@property_accessor'
        tags:
            - { name: twig.extension }
