parameters:
    darvin_admin.cache.clear_command.class: Darvin\AdminBundle\Command\CachesClearCommand
    darvin_admin.cache.clear_command.name:  darvin:admin:caches:clear
    darvin_admin.cache.clear_command.description: >
        Runs cache clear commands specified in "darvin_admin.cache_clear_command_classes" parameter.

    darvin_admin.cache.filesystem.class: Doctrine\Common\Cache\FilesystemCache

    darvin_admin.cache.form_manager.class: Darvin\AdminBundle\Form\CacheFormManager

    darvin_admin.cache.twig_extension.class: Darvin\AdminBundle\Twig\Extension\CacheExtension

services:
    darvin_admin.cache.clear_command:
        class: %darvin_admin.cache.clear_command.class%
        arguments:
            - %darvin_admin.cache.clear_command.name%
            - %darvin_admin.cache.clear_command.description%
        tags:
            - { name: console.command }

    darvin_admin.cache.filesystem:
        class: %darvin_admin.cache.filesystem.class%
        arguments:
            - %kernel.cache_dir%

    darvin_admin.cache.form_manager:
        class: %darvin_admin.cache.form_manager.class%
        arguments:
            - "@form.factory"
            - "@router"
            - "@darvin_utils.templating.provider"

    darvin_admin.cache.twig_extension:
        class:  %darvin_admin.cache.twig_extension.class%
        public: false
        arguments:
            - "@darvin_admin.cache.form_manager"
        tags:
            - { name: twig.extension }
