parameters:
    darvin_admin.ckeditor.compact_form_type.class: Darvin\AdminBundle\Form\Type\CKEditorCompactType

    darvin_admin.ckeditor.controller.class: Darvin\AdminBundle\Controller\CKEditorController

    darvin_admin.ckeditor.form_type.class: Darvin\AdminBundle\Form\Type\CKEditorType

services:
    _defaults:
        public: true

    darvin_admin.ckeditor.compact_form_type:
        class: '%darvin_admin.ckeditor.compact_form_type.class%'
        arguments:
            - '@darvin_utils.locale.provider'
        tags:
            - { name: form.type }

    darvin_admin.ckeditor.controller:
        class: '%darvin_admin.ckeditor.controller.class%'
        tags:
            - { name: controller.service_subscriber }

    darvin_admin.ckeditor.form_type:
        class: '%darvin_admin.ckeditor.form_type.class%'
        arguments:
            - '@darvin_utils.locale.provider'
            - '@property_accessor'
            - '@router'
            - '@darvin_content.translatable.manager'
            - '@darvin_content.widget.pool'
            - '%darvin_admin.ckeditor.plugin_filename%'
            - '%darvin_admin.ckeditor.plugins_path%'
        tags:
            - { name: form.type }
