parameters:
    darvin_admin.ckeditor.form_type.class: Darvin\AdminBundle\Form\Type\CKEditorType

services:
    darvin_admin.ckeditor.form_type:
        class: %darvin_admin.ckeditor.form_type.class%
        arguments:
            - "@request_stack"
            - "@darvin_content.widget.pool"
            - %darvin_admin.ckeditor.plugin_filename%
            - %darvin_admin.ckeditor.plugins_path%
        tags:
            - { name: form.type }
