parameters:
    darvin_admin.configuration.form_type.configurations.class: Darvin\AdminBundle\Form\Type\Configuration\ConfigurationsType

services:
    darvin_admin.configuration.form_type.configurations:
        class: %darvin_admin.configuration.form_type.configurations.class%
        arguments:
            - "@darvin_config.configuration.pool"
        tags:
            - { name: form.type, alias: darvin_admin_configurations }
