parameters:
    darvin_admin.configuration.configurations_form_type.class: Darvin\AdminBundle\Form\Type\Configuration\ConfigurationsType

    darvin_admin.configuration.controller.class: Darvin\AdminBundle\Controller\ConfigurationController

    darvin_admin.configuration.section.class: Darvin\AdminBundle\Configuration\SectionConfiguration

services:
    darvin_admin.configuration.configurations_form_type:
        class: "%darvin_admin.configuration.configurations_form_type.class%"
        arguments:
            - "@darvin_utils.security.accessibility_checker"
            - "@darvin_config.configuration.pool"
        tags:
            - { name: form.type }

    darvin_admin.configuration.controller:
        class: "%darvin_admin.configuration.controller.class%"
        calls:
            - [ setContainer, [ "@service_container" ] ]

    darvin_admin.configuration.section:
        class: "%darvin_admin.configuration.section.class%"
        arguments:
            - "@darvin_utils.object_namer"
            - "%darvin_admin.sections%"
            - "%darvin_admin.entity_override%"
