parameters:
    darvin_admin.crud.action.abstract.class: Darvin\AdminBundle\Controller\Crud\AbstractAction

    darvin_admin.crud.action.batch_delete.class:    Darvin\AdminBundle\Controller\Crud\BatchDeleteAction
    darvin_admin.crud.action.copy.class:            Darvin\AdminBundle\Controller\Crud\CopyAction
    darvin_admin.crud.action.delete.class:          Darvin\AdminBundle\Controller\Crud\DeleteAction
    darvin_admin.crud.action.edit.class:            Darvin\AdminBundle\Controller\Crud\EditAction
    darvin_admin.crud.action.index.class:           Darvin\AdminBundle\Controller\Crud\IndexAction
    darvin_admin.crud.action.new.class:             Darvin\AdminBundle\Controller\Crud\NewAction
    darvin_admin.crud.action.show.class:            Darvin\AdminBundle\Controller\Crud\ShowAction
    darvin_admin.crud.action.update_property.class: Darvin\AdminBundle\Controller\Crud\UpdatePropertyAction

services:
    _defaults:
        public: true

    darvin_admin.crud.action.abstract:
        class:    '%darvin_admin.crud.action.abstract.class%'
        abstract: true
        calls:
            - [ setAdminFormFactory,     [ '@darvin_admin.form.factory' ] ]
            - [ setAdminMetadataManager, [ '@darvin_admin.metadata.manager' ] ]
            - [ setAdminRouter,          [ '@darvin_admin.router' ] ]
            - [ setAuthorizationChecker, [ '@security.authorization_checker' ] ]
            - [ setEntityManager,        [ '@doctrine.orm.entity_manager' ] ]
            - [ setEventDispatcher,      [ '@event_dispatcher' ] ]
            - [ setFlashNotifier,        [ '@darvin_utils.flash.notifier' ] ]
            - [ setRequestStack,         [ '@request_stack' ] ]
            - [ setRouteManager,         [ '@darvin_utils.routing.route_manager' ] ]
            - [ setTemplating,           [ '@templating' ] ]
            - [ setUserManager,          [ '@darvin_user.user.manager' ] ]

    darvin_admin.crud.action.batch_delete:
        class:  '%darvin_admin.crud.action.batch_delete.class%'
        parent: darvin_admin.crud.action.abstract
        public: true

    darvin_admin.crud.action.copy:
        class:  '%darvin_admin.crud.action.copy.class%'
        parent: darvin_admin.crud.action.abstract
        public: true
        arguments:
            - '@darvin_utils.cloner'
            - '@validator'
            - '@darvin_admin.view.widget.pool'

    darvin_admin.crud.action.delete:
        class:  '%darvin_admin.crud.action.delete.class%'
        parent: darvin_admin.crud.action.abstract
        public: true
        arguments:
            - '@darvin_admin.view.widget.pool'

    darvin_admin.crud.action.edit:
        class:  '%darvin_admin.crud.action.edit.class%'
        parent: darvin_admin.crud.action.abstract
        public: true

    darvin_admin.crud.action.index:
        class:  '%darvin_admin.crud.action.index.class%'
        parent: darvin_admin.crud.action.abstract
        public: true
        arguments:
            - '@service_container'
            - '@darvin_utils.custom_object.loader'
            - '@darvin_admin.view.entity_transformer.index'
            - '@darvin_content.filterer'
            - '@darvin_admin.crud.action.new'
            - '@knp_paginator'
            - '@darvin_admin.metadata.sort_criteria_detector'
            - '@darvin_content.sorting.sorted_by_entity_joiner'
            - '@darvin_content.translatable.translation_joiner'
            - '@darvin_utils.user.query_builder_filterer'

    darvin_admin.crud.action.new:
        class:  '%darvin_admin.crud.action.new.class%'
        parent: darvin_admin.crud.action.abstract
        public: true
        arguments:
            - '@darvin_admin.form.handler.new_action_filter'
            - '@property_accessor'
            - '@darvin_content.translatable.translations_initializer'
            - '@darvin_content.translatable.translation_joiner'
            - '%darvin_admin.locales%'

    darvin_admin.crud.action.show:
        class:  '%darvin_admin.crud.action.show.class%'
        parent: darvin_admin.crud.action.abstract
        public: true
        arguments:
            - '@darvin_utils.custom_object.loader'
            - '@darvin_admin.view.entity_transformer.show'

    darvin_admin.crud.action.update_property:
        class:  '%darvin_admin.crud.action.update_property.class%'
        parent: darvin_admin.crud.action.abstract
        public: true
        arguments:
            - '@darvin_admin.view.entity_transformer.index'
            - '@translator'
