parameters:
    darvin_admin.crud.action.abstract.class: Darvin\AdminBundle\Controller\Crud\Action\AbstractAction

    darvin_admin.crud.action.index.class: Darvin\AdminBundle\Controller\Crud\Action\IndexAction
    darvin_admin.crud.action.new.class:   Darvin\AdminBundle\Controller\Crud\Action\NewAction
    darvin_admin.crud.action.show.class:  Darvin\AdminBundle\Controller\Crud\Action\ShowAction

    darvin_admin.crud.controller.class: Darvin\AdminBundle\Controller\Crud\CrudController

services:
    _defaults:
        public: true

    darvin_admin.crud.action.abstract:
        class:    '%darvin_admin.crud.action.abstract.class%'
        abstract: true
        calls:
            - [ setAdminFormFactory,     [ '@darvin_admin.form.factory' ] ]
            - [ setAdminMetadataManager, [ '@darvin_admin.metadata.manager' ] ]
            - [ setAdminRouter,          [ '@darvin_admin.router' ] ]
            - [ setAuthorizationChecker, [ '@security.authorization_checker' ] ]
            - [ setEntityManager,        [ '@doctrine.orm.entity_manager' ] ]
            - [ setEventDispatcher,      [ '@event_dispatcher' ] ]
            - [ setFlashNotifier,        [ '@darvin_utils.flash.notifier' ] ]
            - [ setTemplating,           [ '@templating' ] ]
            - [ setUserManager,          [ '@darvin_user.user.manager' ] ]

    darvin_admin.crud.action.index:
        class:  '%darvin_admin.crud.action.index.class%'
        parent: darvin_admin.crud.action.abstract
        public: false
        arguments:
            - '@service_container'
            - '@darvin_utils.custom_object.loader'
            - '@darvin_admin.view.entity_transformer.index'
            - '@darvin_content.filterer'
            - '@darvin_admin.crud.action.new'
            - '@knp_paginator'
            - '@darvin_admin.metadata.sort_criteria_detector'
            - '@darvin_content.sorting.sorted_by_entity_joiner'
            - '@darvin_content.translatable.translation_joiner'
            - '@darvin_utils.user.query_builder_filterer'
        tags:
            - { name: darvin_admin.crud.action }

    darvin_admin.crud.action.new:
        class:  '%darvin_admin.crud.action.new.class%'
        parent: darvin_admin.crud.action.abstract
        public: false
        arguments:
            - '@darvin_admin.form.handler.new_action_filter'
            - '@property_accessor'
            - '@darvin_content.translatable.translations_initializer'
            - '@darvin_content.translatable.translation_joiner'
            - '%darvin_admin.locales%'
        tags:
            - { name: darvin_admin.crud.action }

    darvin_admin.crud.action.show:
        class:  '%darvin_admin.crud.action.show.class%'
        parent: darvin_admin.crud.action.abstract
        public: false
        arguments:
            - '@darvin_utils.custom_object.loader'
            - '@darvin_admin.view.entity_transformer.show'
        tags:
            - { name: darvin_admin.crud.action }

    darvin_admin.crud.controller:
        class:    '%darvin_admin.crud.controller.class%'
        abstract: true
        arguments:
            - '@darvin_admin.metadata.manager'
        calls:
            - [ setContainer, [ '@service_container' ] ]
