parameters:
    darvin_admin.crud.controller.class: Darvin\AdminBundle\Controller\CrudController

services:
    _defaults:
        public: true

    darvin_admin.crud.controller:
        class:    "%darvin_admin.crud.controller.class%"
        abstract: true
        arguments:
            - "@darvin_admin.metadata.manager"
        calls:
            - [ setContainer, [ "@service_container" ] ]
