parameters:
    darvin_admin.crud.action.abstract.class: Darvin\AdminBundle\Controller\Crud\Action\AbstractAction

    darvin_admin.crud.action.show.class: Darvin\AdminBundle\Controller\Crud\Action\ShowAction

    darvin_admin.crud.controller.class: Darvin\AdminBundle\Controller\Crud\CrudController

services:
    _defaults:
        public: true

    darvin_admin.crud.action.abstract:
        class:    '%darvin_admin.crud.action.abstract.class%'
        abstract: true
        calls:
            - [ setAdminMetadataManager, [ '@darvin_admin.metadata.manager' ] ]
            - [ setAuthorizationChecker, [ '@security.authorization_checker' ] ]
            - [ setEntityManager,        [ '@doctrine.orm.entity_manager' ] ]
            - [ setEventDispatcher,      [ '@event_dispatcher' ] ]
            - [ setTemplating,           [ '@templating' ] ]
            - [ setUserManager,          [ '@darvin_user.user.manager' ] ]

    darvin_admin.crud.action.show:
        class:  '%darvin_admin.crud.action.show.class%'
        parent: darvin_admin.crud.action.abstract
        public: false
        arguments:
            - '@darvin_utils.custom_object.loader'
            - '@darvin_admin.view.entity_transformer.show'
        tags:
            - { name: darvin_admin.crud.action }

    darvin_admin.crud.controller:
        class:    '%darvin_admin.crud.controller.class%'
        abstract: true
        arguments:
            - '@darvin_admin.metadata.manager'
        calls:
            - [ setContainer, [ '@service_container' ] ]
