parameters:
    darvin_admin.dropzone.form_type.class: Darvin\AdminBundle\Form\Type\DropzoneType

services:
    darvin_admin.dropzone.form_type:
        class: %darvin_admin.dropzone.form_type.class%
        arguments:
            - "@oneup_uploader.templating.uploader_helper"
        tags:
            - { name: form.type, alias: darvin_admin_dropzone }