parameters:
    darvin_admin.entity_namer.class: Darvin\AdminBundle\EntityNamer\EntityNamer

services:
    _defaults:
        public: true

    darvin_admin.entity_namer:
        class: '%darvin_admin.entity_namer.class%'
        arguments:
            - '@darvin_utils.orm.entity_resolver'
            - '@darvin_utils.object_namer'
            - '@darvin_admin.configuration.section'
