parameters:
    darvin_admin.error.show_error_page_listener.class:          Darvin\AdminBundle\EventListener\ShowErrorPageListener
    darvin_admin.error.show_error_page_listener.firewall_name:  admin_area
    darvin_admin.error.show_error_page_listener.homepage_route: darvin_admin_homepage

services:
    _defaults:
        public: true

    darvin_admin.error.show_error_page_listener:
        class: '%darvin_admin.error.show_error_page_listener.class%'
        arguments:
            - '@security.firewall.map'
            - '@logger'
            - '@router'
            - '@templating'
            - '@translator'
            - '%darvin_admin.error.show_error_page_listener.firewall_name%'
            - '%darvin_admin.error.show_error_page_listener.homepage_route%'
            - '%locales%'
            - '%locale%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
