parameters:
    darvin_admin.form.group_form_type_extension.class: Darvin\AdminBundle\Form\Extension\GroupFormTypeExtension

    darvin_admin.form.help_file_type_extension.class: Darvin\AdminBundle\Form\Extension\HelpFileTypeExtension

    darvin_admin.form.factory.class: Darvin\AdminBundle\Form\AdminFormFactory

    darvin_admin.form.manipulator.class: Darvin\AdminBundle\Form\Manipulator

    darvin_admin.form.renderer.property.class: Darvin\AdminBundle\Form\Renderer\PropertyFormRenderer

    darvin_admin.form.type.entity.class: Darvin\AdminBundle\Form\Type\EntityType

    darvin_admin.form.type.filter.class: Darvin\AdminBundle\Form\Type\FilterType

    darvin_admin.form.type.position.class: Darvin\AdminBundle\Form\Type\PositionType

    darvin_admin.form.type.translatable.class: Darvin\AdminBundle\Form\Type\TranslatableType

services:
    darvin_admin.form.group_form_type_extension:
        class: '%darvin_admin.form.group_form_type_extension.class%'
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    darvin_admin.form.help_file_type_extension:
        class: '%darvin_admin.form.help_file_type_extension.class%'
        arguments:
            - '@translator'
            - '%darvin_admin.upload_max_size_mb%'
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }

    darvin_admin.form.factory:
        class: '%darvin_admin.form.factory.class%'
        arguments:
            - '@darvin_admin.router'
            - '@form.factory'
            - '@darvin_admin.metadata.identifier_accessor'
            - '@property_accessor'

    darvin_admin.form.manipulator:
        class:  '%darvin_admin.form.manipulator.class%'
        parent: a2lix_auto_form.form.manipulator.doctrine_orm_manipulator

    darvin_admin.form.renderer.property:
        class: '%darvin_admin.form.renderer.property.class%'
        arguments:
            - '@form.property_accessor'
            - '@twig'

    darvin_admin.form.type.entity:
        class: '%darvin_admin.form.type.entity.class%'
        arguments:
            - '@security.authorization_checker'
            - '@form.registry'
            - '@darvin_content.translatable.manager'
            - '%darvin_admin.form.default_field_options%'
        tags:
            - { name: form.type }

    darvin_admin.form.type.filter:
        class: '%darvin_admin.form.type.filter.class%'
        arguments:
            - '@security.authorization_checker'
            - '@form.registry'
            - '@darvin_content.translatable.translation_joiner'
            - '%darvin_admin.form.default_field_options%'
        tags:
            - { name: form.type }

    darvin_admin.form.type.position:
        class: '%darvin_admin.form.type.position.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@property_accessor'
            - '@stof_doctrine_extensions.listener.tree'
        tags:
            - { name: form.type }

    darvin_admin.form.type.translatable:
        class: '%darvin_admin.form.type.translatable.class%'
        arguments:
            - '%locales%'
        tags:
            - { name: form.type }
