parameters:
    darvin_admin.form.factory.class: Darvin\AdminBundle\Form\AdminFormFactory

    darvin_admin.form.handler.class: Darvin\AdminBundle\Form\FormHandler

    darvin_admin.form.type_extension.info.class: Darvin\AdminBundle\Form\Type\Extension\InfoExtension

services:
    darvin_admin.form.factory:
        class: %darvin_admin.form.factory.class%
        arguments:
            - "@darvin_admin.route.router"
            - "@form.factory"
            - "@form.type_guesser.doctrine"
            - "@darvin_admin.metadata.identifier_accessor"
            - "@darvin_admin.metadata.manager"

    darvin_admin.form.handler:
        class: %darvin_admin.form.handler.class%
        arguments:
            - "@darvin_utils.cloner"
            - "@doctrine.orm.entity_manager"
            - "@darvin_utils.flash.notifier"
            - "@darvin_admin.metadata.manager"
            - "@validator"

    darvin_admin.form.type_extension.info:
        class: %darvin_admin.form.type_extension.info.class%
        tags:
            - { name: form.type_extension, alias: form }
