parameters:
    darvin_admin.image.twig_extension.class: Darvin\AdminBundle\Twig\Extension\ImageExtension

services:
    darvin_admin.image.twig_extension:
        class:  "%darvin_admin.image.twig_extension.class%"
        public: false
        arguments:
            - "@darvin_admin.configuration"
            - "@darvin_image.url_builder.filter.resize"
        tags:
            - { name: twig.extension }
