parameters:
    darvin_admin.log.metadata.entity: Darvin\AdminBundle\Entity\LogEntry
    darvin_admin.log.metadata.config: "@@DarvinAdminBundle/Resources/config/admin/log.yml"

services:
    darvin_admin.log.metadata:
        parent: darvin_admin.metadata.abstract
        arguments:
            - %darvin_admin.log.metadata.entity%
            - %darvin_admin.log.metadata.config%
        tags:
            - { name: darvin_admin.metadata }
