parameters:
    darvin_admin.menu.class: Darvin\AdminBundle\Menu\Menu

    darvin_admin.menu.configuration_item_factory.class: Darvin\AdminBundle\Menu\ConfigurationItemFactory

    darvin_admin.menu.item_factory.class: Darvin\AdminBundle\Menu\ItemFactory

    darvin_admin.menu.twig_extension.class: Darvin\AdminBundle\Twig\Extension\MenuExtension

services:
    darvin_admin.menu:
        class:  "%darvin_admin.menu.class%"
        public: false
        arguments:
            - "@security.authorization_checker"
            - "%darvin_admin.menu.groups%"

    darvin_admin.menu.configuration_item_factory:
        class:  "%darvin_admin.menu.configuration_item_factory.class%"
        public: false
        arguments:
            - "@security.authorization_checker"
            - "@router"
        tags:
            - { name: darvin_admin.menu_item_factory }

    darvin_admin.menu.item_factory:
        class:  "%darvin_admin.menu.item_factory.class%"
        public: false
        arguments:
            - "@darvin_admin.route.router"
            - "@security.authorization_checker"
            - "@darvin_admin.metadata.manager"
        tags:
            - { name: darvin_admin.menu_item_factory }

    darvin_admin.menu.twig_extension:
        class:  "%darvin_admin.menu.twig_extension.class%"
        public: false
        arguments:
            - "@darvin_admin.menu"
        tags:
            - { name: twig.extension }
