parameters:
    darvin_admin.menu.twig_extension.class: Darvin\AdminBundle\Twig\Extension\MenuExtension

services:
    darvin_admin.menu.twig_extension:
        class:  %darvin_admin.menu.twig_extension.class%
        public: false
        tags:
            - { name: twig.extension }
