parameters:
    darvin_admin.menu.class: Darvin\AdminBundle\Menu\Menu

    darvin_admin.menu.item_factory.configuration.class: Darvin\AdminBundle\Menu\Factory\ConfigurationItemFactory

    darvin_admin.menu.item_factory.section.class: Darvin\AdminBundle\Menu\Factory\SectionItemFactory

    darvin_admin.menu.twig_extension.class: Darvin\AdminBundle\Twig\Extension\MenuExtension

services:
    _defaults:
        public: true

    darvin_admin.menu:
        class:  '%darvin_admin.menu.class%'
        public: false
        arguments:
            - '@darvin_utils.new_object.counter'
            - '@request_stack'
            - '%darvin_admin.menu.groups%'

    darvin_admin.menu.item_factory.configuration:
        class:  '%darvin_admin.menu.item_factory.configuration.class%'
        public: false
        arguments:
            - '@security.authorization_checker'
            - '@router'
        tags:
            - { name: darvin_admin.menu_item_factory }

    darvin_admin.menu.item_factory.section:
        class:  '%darvin_admin.menu.item_factory.section.class%'
        public: false
        arguments:
            - '@darvin_admin.router'
            - '@security.authorization_checker'
            - '@doctrine.orm.entity_manager'
            - '@darvin_admin.metadata.manager'
        tags:
            - { name: darvin_admin.menu_item_factory }

    darvin_admin.menu.twig_extension:
        class:  '%darvin_admin.menu.twig_extension.class%'
        public: false
        arguments:
            - '@darvin_admin.menu'
        tags:
            - { name: twig.extension }
