parameters:
    darvin_admin.menu.class: Darvin\AdminBundle\Menu\Menu

    darvin_admin.menu.factory.group.class: Darvin\AdminBundle\Menu\Factory\GroupFactory

    darvin_admin.menu.factory.item.configuration.class: Darvin\AdminBundle\Menu\Factory\Item\ConfigurationItemFactory

    darvin_admin.menu.factory.item.section.class: Darvin\AdminBundle\Menu\Factory\Item\SectionItemFactory

    darvin_admin.menu.factory.separator.class: Darvin\AdminBundle\Menu\Factory\SeparatorFactory

    darvin_admin.menu.twig_extension.class: Darvin\AdminBundle\Twig\Extension\MenuExtension

services:
    _defaults:
        public: true

    darvin_admin.menu:
        class:  '%darvin_admin.menu.class%'
        public: false
        arguments:
            - '@darvin_utils.new_object.counter'
            - '@request_stack'

    darvin_admin.menu.factory.group:
        class: '%darvin_admin.menu.factory.group.class%'
        arguments:
            - '%darvin_admin.menu.groups%'
        tags:
            - { name: darvin_admin.menu_item_factory }

    darvin_admin.menu.factory.item.configuration:
        class:  '%darvin_admin.menu.factory.item.configuration.class%'
        public: false
        arguments:
            - '@security.authorization_checker'
            - '@router'
        tags:
            - { name: darvin_admin.menu_item_factory }

    darvin_admin.menu.factory.item.section:
        class:  '%darvin_admin.menu.factory.item.section.class%'
        public: false
        arguments:
            - '@darvin_admin.router'
            - '@security.authorization_checker'
            - '@doctrine.orm.entity_manager'
            - '@darvin_admin.metadata.manager'
        tags:
            - { name: darvin_admin.menu_item_factory }

    darvin_admin.menu.factory.separator:
        class: '%darvin_admin.menu.factory.separator.class%'
        arguments:
            - '%darvin_admin.menu.groups%'
        tags:
            - { name: darvin_admin.menu_item_factory }

    darvin_admin.menu.twig_extension:
        class:  '%darvin_admin.menu.twig_extension.class%'
        public: false
        arguments:
            - '@darvin_admin.menu'
        tags:
            - { name: twig.extension }
