parameters:
    darvin_admin.metadata.abstract.class: Darvin\AdminBundle\Metadata\Metadata

    darvin_admin.metadata.configuration.loader.class: Darvin\AdminBundle\Metadata\Configuration\ConfigurationLoader

    darvin_admin.metadata.factory.class: Darvin\AdminBundle\Metadata\MetadataFactory

    darvin_admin.metadata.identifier_accessor.class: Darvin\AdminBundle\Metadata\IdentifierAccessor

    darvin_admin.metadata.manager.class: Darvin\AdminBundle\Metadata\MetadataManager

    darvin_admin.metadata.pool.class: Darvin\AdminBundle\Metadata\MetadataPool

    darvin_admin.metadata.sort_criteria_detector.class: Darvin\AdminBundle\Metadata\SortCriteriaDetector

services:
    _defaults:
        public: true

    darvin_admin.metadata.abstract:
        class:    '%darvin_admin.metadata.abstract.class%'
        factory:  [ '@darvin_admin.metadata.factory', createMetadata ]
        abstract: true
        public:   false

    darvin_admin.metadata.configuration.loader:
        class:  '%darvin_admin.metadata.configuration.loader.class%'
        public: false
        arguments:
            - '@logger'
            - '@=service("service_container").getParameterBag()'
            - '%kernel.bundles%'
            - '%kernel.project_dir%'

    darvin_admin.metadata.factory:
        class:  '%darvin_admin.metadata.factory.class%'
        public: false
        arguments:
            - '@darvin_admin.metadata.configuration.loader'
            - '@doctrine.orm.entity_manager'
            - '@darvin_content.translatable.manager'

    darvin_admin.metadata.identifier_accessor:
        class: '%darvin_admin.metadata.identifier_accessor.class%'
        arguments:
            - '@darvin_admin.metadata.manager'
            - '@property_accessor'

    darvin_admin.metadata.manager:
        class: '%darvin_admin.metadata.manager.class%'
        arguments:
            - '@darvin_utils.orm.entity_resolver'
            - '@event_dispatcher'
            - '@darvin_admin.metadata.pool'
        calls:
            - [ setCache, [ '@?darvin_admin.cache' ] ]

    darvin_admin.metadata.pool:
        class: '%darvin_admin.metadata.pool.class%'
        lazy:  true

    darvin_admin.metadata.sort_criteria_detector:
        class: '%darvin_admin.metadata.sort_criteria_detector.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@darvin_admin.metadata.manager'
            - '@stof_doctrine_extensions.listener.sortable'
            - '@stof_doctrine_extensions.listener.tree'
