darvin_admin_import_ckeditor:
    resource: '@DarvinAdminBundle/Resources/config/routing/ckeditor.yaml'
    prefix:   /ckeditor

darvin_admin_import_configuration:
    resource: '@DarvinAdminBundle/Resources/config/routing/configuration.yaml'
    prefix:   /configuration

darvin_admin_import_image:
    resource: '@DarvinImageBundle/Resources/config/routing.yaml'
    prefix:   /image

darvin_admin_import_search:
    resource: '@DarvinAdminBundle/Resources/config/routing/search.yaml'
    prefix:   /search

darvin_admin_import_fm_elfinder:
    resource: '@FMElfinderBundle/Resources/config/routing.yml'

darvin_admin_import_loader:
    resource: .
    type:     darvin_admin

darvin_admin_import_security:
    resource: '@DarvinAdminBundle/Resources/config/routing/security.yaml'

darvin_admin_import_homepage:
    resource: '@DarvinAdminBundle/Resources/config/routing/homepage.yaml'
