parameters:
    darvin_admin.route.loader.class: Darvin\AdminBundle\Route\RouteLoader

    darvin_admin.route.twig_extension.class: Darvin\AdminBundle\Twig\Extension\RouteExtension

    darvin_admin.router.class: Darvin\AdminBundle\Route\AdminRouter

services:
    darvin_admin.route.loader:
        class: '%darvin_admin.route.loader.class%'
        arguments:
            - '@darvin_admin.metadata.manager'
        tags:
            - { name: routing.loader }

    darvin_admin.route.twig_extension:
        class: '%darvin_admin.route.twig_extension.class%'
        arguments:
            - '@darvin_admin.router'
        tags:
            - { name: twig.extension }

    darvin_admin.router:
        class: '%darvin_admin.router.class%'
        arguments:
            - '@darvin_utils.orm.entity_resolver'
            - '@router'
            - '@darvin_admin.metadata.identifier_accessor'
            - '@darvin_admin.metadata.manager'
            - '@property_accessor'
            - '@request_stack'
            - '@darvin_utils.routing.route_manager'
