import_configuration:
    resource: "@DarvinAdminBundle/Resources/config/routing/configuration.yml"
    prefix:   /configuration

import_security:
    resource: "@DarvinAdminBundle/Resources/config/routing/security.yml"
    prefix:   /

import_homepage:
    resource: "@DarvinAdminBundle/Resources/config/routing/homepage.yml"
    prefix:   /
