darvin_admin_import_autocomplete:
    resource: '@DarvinAdminBundle/Resources/config/routing/autocomplete.yaml'
    prefix:   /autocomplete

darvin_admin_import_cache:
    resource: '@DarvinAdminBundle/Resources/config/routing/cache/routing.yaml'
    prefix:   /cache

darvin_admin_import_ckeditor:
    resource: '@DarvinAdminBundle/Resources/config/routing/ckeditor.yaml'
    prefix:   /ckeditor

darvin_admin_import_configuration:
    resource: '@DarvinAdminBundle/Resources/config/routing/configuration.yaml'
    prefix:   /config

darvin_admin_import_image:
    resource: '@DarvinImageBundle/Resources/config/routing.yaml'
    prefix:   /image

darvin_admin_import_search:
    resource: '@DarvinAdminBundle/Resources/config/routing/search.yaml'
    prefix:   /search

darvin_admin_import_fm_elfinder:
    resource: '@FMElfinderBundle/Resources/config/routing.yaml'

darvin_admin_import_loader:
    resource: .
    type:     darvin_admin

darvin_admin_import_page:
    resource: '@DarvinAdminBundle/Resources/config/routing/page.yaml'

darvin_admin_import_security:
    resource: '@DarvinAdminBundle/Resources/config/routing/security.yaml'

darvin_admin_import_homepage:
    resource: '@DarvinAdminBundle/Resources/config/routing/homepage.yaml'
