parameters:
    darvin_admin.security.authorization_voter.class: Darvin\AdminBundle\Security\Authorization\Voter\AdminVoter

    darvin_admin.security.configuration.entity.abstract.class: Darvin\AdminBundle\Security\Configuration\EntitySecurityConfiguration

    darvin_admin.security.configuration.pool.class: Darvin\AdminBundle\Security\Configuration\SecurityConfigurationPool

    darvin_admin.security.form_type.object_permissions.class: Darvin\AdminBundle\Form\Type\Security\Permissions\ObjectPermissionsType

    darvin_admin.security.user_provider.oauth.class: Darvin\AdminBundle\Security\User\OAuthUserProvider

services:
    darvin_admin.security.authorization_voter:
        class:  "%darvin_admin.security.authorization_voter.class%"
        public: false
        arguments:
            - "@darvin_admin.security.configuration.pool"
        tags:
            - { name: security.voter }

    darvin_admin.security.configuration.entity.abstract:
        class:    "%darvin_admin.security.configuration.entity.abstract.class%"
        abstract: true
        public:   false

    darvin_admin.security.configuration.pool:
        class: "%darvin_admin.security.configuration.pool.class%"

    darvin_admin.security.form_type.object_permissions:
        class: "%darvin_admin.security.form_type.object_permissions.class%"
        arguments:
            - "@darvin_user.user.repository"
        tags:
            - { name: form.type }

    darvin_admin.security.user_provider.oauth:
        class:  "%darvin_admin.security.user_provider.oauth.class%"
        parent: darvin_user.security.user_provider.oauth
