parameters:
    darvin_admin.security.user_provider.administrator.class: Darvin\AdminBundle\Security\User\AdministratorUserProvider

services:
    darvin_admin.security.user_provider.administrator:
        class: %darvin_admin.security.user_provider.administrator.class%
        arguments:
            - "@doctrine.orm.entity_manager"
