parameters:
    darvin_admin.security.form_type.object_permissions.class: Darvin\AdminBundle\Form\Type\Security\Permissions\ObjectPermissionsType

    darvin_admin.security.user_provider.administrator.class: Darvin\AdminBundle\Security\User\AdministratorUserProvider

    darvin_admin.security.user_provider.oauth.class: Darvin\AdminBundle\Security\User\OAuth\OAuthUserProvider

services:
    darvin_admin.security.form_type.object_permissions:
        class: %darvin_admin.security.form_type.object_permissions.class%
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: darvin_admin_security_object_permissions }

    darvin_admin.security.user_provider.administrator:
        class: %darvin_admin.security.user_provider.administrator.class%
        arguments:
            - "@doctrine.orm.entity_manager"

    darvin_admin.security.user_provider.oauth:
        class: %darvin_admin.security.user_provider.oauth.class%
