parameters:
    darvin_admin.security.authorization_voter.class: Darvin\AdminBundle\Security\Authorization\Voter\AdminVoter

    darvin_admin.security.oauth.darvin_auth_user_provider.class: Darvin\AdminBundle\Security\OAuth\DarvinAuthUserProvider

services:
    _defaults:
        public: true

    darvin_admin.security.authorization_voter:
        class:  '%darvin_admin.security.authorization_voter.class%'
        public: false
        arguments:
            - '@darvin_utils.orm.entity_resolver'
            - '@darvin_admin.metadata.manager'
            - '@darvin_user.role.configuration'
            - '%darvin_admin.permissions%'
        tags:
            - { name: security.voter }

    darvin_admin.security.oauth.darvin_auth_user_provider:
        class:  '%darvin_admin.security.oauth.darvin_auth_user_provider.class%'
        parent: darvin_user.security.oauth.darvin_auth_user_provider
        public: true
