parameters:
    darvin_admin.security.user_provider.administrator.class: Darvin\AdminBundle\Security\User\AdministratorUserProvider

    darvin_admin.security.user_provider.oauth.class: Darvin\AdminBundle\Security\User\OAuth\OAuthUserProvider

services:
    darvin_admin.security.user_provider.administrator:
        class: %darvin_admin.security.user_provider.administrator.class%
        arguments:
            - "@doctrine.orm.entity_manager"

    darvin_admin.security.user_provider.oauth:
        class: %darvin_admin.security.user_provider.oauth.class%
