parameters:
    darvin_admin.security.authorization_voter.class: Darvin\AdminBundle\Security\Authorization\Voter\AdminVoter

    darvin_admin.security.configuration_pool.class: Darvin\AdminBundle\Security\Configuration\SecurityConfigurationPool

    darvin_admin.security.form_type.object_permissions.class: Darvin\AdminBundle\Form\Type\Security\Permissions\ObjectPermissionsType

    darvin_admin.security.user_provider.administrator.class: Darvin\AdminBundle\Security\User\AdministratorUserProvider

    darvin_admin.security.user_provider.oauth_administrator.class: Darvin\AdminBundle\Security\User\OAuthAdministratorUserProvider

services:
    darvin_admin.security.authorization_voter:
        class: %darvin_admin.security.authorization_voter.class%
        arguments:
            - "@darvin_admin.security.configuration_pool"
        tags:
            - { name: security.voter }

    darvin_admin.security.configuration_pool:
        class: %darvin_admin.security.configuration_pool.class%

    darvin_admin.security.form_type.object_permissions:
        class: %darvin_admin.security.form_type.object_permissions.class%
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: darvin_admin_security_object_permissions }

    darvin_admin.security.user_provider.administrator:
        class: %darvin_admin.security.user_provider.administrator.class%
        arguments:
            - "@doctrine.orm.entity_manager"

    darvin_admin.security.user_provider.oauth_administrator:
        class: %darvin_admin.security.user_provider.oauth_administrator.class%
        arguments:
            - "@doctrine.orm.entity_manager"
