parameters:
    darvin_admin.security.authorization_voter.class: Darvin\AdminBundle\Security\Authorization\Voter\AdminVoter

    darvin_admin.security.configuration.abstract.class: Darvin\AdminBundle\Security\Configuration\SecurityConfiguration

    darvin_admin.security.configuration.pool.class: Darvin\AdminBundle\Security\Configuration\SecurityConfigurationPool

    darvin_admin.security.form_type.object_permissions.class: Darvin\AdminBundle\Form\Type\Security\Permissions\ObjectPermissionsType

    darvin_admin.security.oauth.user_provider.class: Darvin\AdminBundle\Security\OAuth\OAuthUserProvider

services:
    _defaults:
        public: true

    darvin_admin.security.authorization_voter:
        class:  '%darvin_admin.security.authorization_voter.class%'
        public: false
        arguments:
            - '@darvin_utils.orm.entity_resolver'
            - '@darvin_admin.metadata.manager'
            - '@darvin_admin.security.configuration.pool'
        tags:
            - { name: security.voter }

    darvin_admin.security.configuration.abstract:
        class:    '%darvin_admin.security.configuration.abstract.class%'
        abstract: true
        public:   false

    darvin_admin.security.configuration.pool:
        class:  '%darvin_admin.security.configuration.pool.class%'
        public: false

    darvin_admin.security.form_type.object_permissions:
        class: '%darvin_admin.security.form_type.object_permissions.class%'
        arguments:
            - '@darvin_user.user.repository'
        tags:
            - { name: form.type }

    darvin_admin.security.oauth.user_provider:
        class:  '%darvin_admin.security.oauth.user_provider.class%'
        parent: darvin_user.security.oauth.user_provider
        public: true
