parameters:
    darvin_admin.slug_suffix.form_type.class: Darvin\AdminBundle\Form\Type\SlugSuffixType

services:
    darvin_admin.slug_suffix.form_type:
        class: %darvin_admin.slug_suffix.form_type.class%
        arguments:
            - "@router"
            - "@darvin_utils.sluggable.manager"
        tags:
            - { name: form.type }
