parameters:
    darvin_admin.slug_suffix.form_type.class: Darvin\AdminBundle\Form\Type\SlugSuffixType

services:
    darvin_admin.slug_suffix.form_type:
        class: "%darvin_admin.slug_suffix.form_type.class%"
        arguments:
            - "@property_accessor"
            - "@router"
        tags:
            - { name: form.type }
