parameters:
    darvin_admin.slug_suffix.form_type.class: Darvin\AdminBundle\Form\Type\SlugSuffixType

services:
    _defaults:
        public: true

    darvin_admin.slug_suffix.form_type:
        class: '%darvin_admin.slug_suffix.form_type.class%'
        arguments:
            - '@darvin_utils.homepage.provider'
            - '@property_accessor'
            - '@darvin_utils.routing.route_manager'
        tags:
            - { name: form.type }
