parameters:
    darvin_admin.translation.clear_cache_listener.class: Darvin\AdminBundle\EventListener\ClearTranslationCacheListener

    darvin_admin.translation.generate_command.class: Darvin\AdminBundle\Command\GenerateTranslationsCommand
    darvin_admin.translation.generate_command.name:  darvin:admin:translations:generate

services:
    darvin_admin.translation.clear_cache_listener:
        class:  "%darvin_admin.translation.clear_cache_listener.class%"
        public: false
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    darvin_admin.translation.generate_command:
        class: "%darvin_admin.translation.generate_command.class%"
        arguments:
            - "%darvin_admin.translation.generate_command.name%"
            - "@doctrine.orm.entity_manager"
            - "@darvin_admin.entity_namer"
            - "%locale%"
            - "%locales%"
            - "%darvin_admin.translations_model_dir%"
        tags:
            - { name: console.command }
