parameters:
    darvin_admin.translation.clear_cache_listener.class: Darvin\AdminBundle\EventListener\ClearTranslationCacheListener

services:
    _defaults:
        public: true

    darvin_admin.translation.clear_cache_listener:
        class:  "%darvin_admin.translation.clear_cache_listener.class%"
        public: false
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: onFlush }
