parameters:
    darvin_admin.twig.globals_extension.class: Darvin\AdminBundle\Twig\Extension\GlobalsExtension

services:
    darvin_admin.twig.globals_extension:
        class: %darvin_admin.twig.globals_extension.class%
        arguments:
            - %darvin_admin.project.title%
            - %darvin_admin.project.url%
        tags:
            - { name: twig.extension }
