parameters:
    darvin_admin.twig.globals.class: Darvin\AdminBundle\Twig\Globals

services:
    _defaults:
        public: true

    darvin_admin.twig.globals:
        class:  '%darvin_admin.twig.globals.class%'
        public: false
        arguments:
            - '%darvin_admin.frontend_path%'
            - '%darvin_admin.locales%'
            - '%darvin_admin.logo%'
            - '%darvin_admin.project_title%'
            - '%darvin_admin.assets.scripts%'
            - '%darvin_admin.assets.styles%'
            - '%darvin_admin.yandex_translate_api_key%'
