parameters:
    darvin_admin.uploader.listener.class: Darvin\AdminBundle\EventListener\UploaderListener

services:
    darvin_admin.uploader.listener:
        class: "%darvin_admin.uploader.listener.class%"
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_upload, method: postUpload }
