parameters:
    darvin_admin.view.entity_transformer.abstract.class: Darvin\AdminBundle\View\AbstractEntityToViewTransformer

    darvin_admin.view.entity_transformer.index.class: Darvin\AdminBundle\View\Index\EntitiesToIndexViewTransformer

    darvin_admin.view.entity_transformer.show.class: Darvin\AdminBundle\View\Show\EntityToShowViewTransformer

    darvin_admin.view.widget_generator.abstract.class: Darvin\AdminBundle\View\WidgetGenerator\AbstractWidgetGenerator

    darvin_admin.view.widget_generator.actions.class: Darvin\AdminBundle\View\WidgetGenerator\ActionsGenerator

    darvin_admin.view.widget_generator.child_links.class: Darvin\AdminBundle\View\WidgetGenerator\ChildLinksGenerator

    darvin_admin.view.widget_generator.delete_form.class: Darvin\AdminBundle\View\WidgetGenerator\DeleteFormGenerator

    darvin_admin.view.widget_generator.edit_link.class: Darvin\AdminBundle\View\WidgetGenerator\EditLinkGenerator

    darvin_admin.view.widget_generator.email_link.class: Darvin\AdminBundle\View\WidgetGenerator\EmailLinkGenerator

    darvin_admin.view.widget_generator.image_link.class: Darvin\AdminBundle\View\WidgetGenerator\ImageLinkGenerator

    darvin_admin.view.widget_generator.list.class: Darvin\AdminBundle\View\WidgetGenerator\ListGenerator

    darvin_admin.view.widget_generator.show_link.class: Darvin\AdminBundle\View\WidgetGenerator\ShowLinkGenerator

    darvin_admin.view.widget_generator.pool.class: Darvin\AdminBundle\View\WidgetGenerator\WidgetGeneratorPool

    darvin_admin.view.widget_generator.pool_provider.class: Darvin\AdminBundle\View\WidgetGenerator\WidgetGeneratorPoolProvider

    darvin_admin.view.widget_generator.twig_extension.class: Darvin\AdminBundle\Twig\Extension\ViewWidgetGeneratorExtension

services:
    darvin_admin.view.entity_transformer.abstract:
        class:    %darvin_admin.view.entity_transformer.abstract.class%
        abstract: true
        arguments:
            - "@service_container"
            - "@darvin_admin.metadata.manager"
            - "@property_accessor"
            - "@darvin_admin.stringifier"
            - "@translator"
            - "@darvin_admin.view.widget_generator.pool"

    darvin_admin.view.entity_transformer.index:
        class:  %darvin_admin.view.entity_transformer.index.class%
        parent: darvin_admin.view.entity_transformer.abstract
        calls:
            - [ setFormFactory, [ "@form.factory" ] ]
            - [ setTemplating,  [ "@templating" ] ]

    darvin_admin.view.entity_transformer.show:
        class:  %darvin_admin.view.entity_transformer.show.class%
        parent: darvin_admin.view.entity_transformer.abstract

    darvin_admin.view.widget_generator.abstract:
        class:    %darvin_admin.view.widget_generator.abstract.class%
        abstract: true
        arguments:
            - "@darvin_admin.metadata.manager"
            - "@templating"

    darvin_admin.view.widget_generator.actions:
        class:  %darvin_admin.view.widget_generator.actions.class%
        parent: darvin_admin.view.widget_generator.abstract
        calls:
            - [ setWidgetGeneratorPool, [ "@darvin_admin.view.widget_generator.pool" ] ]
        tags:
            - { name: darvin_admin.view.widget_generator }

    darvin_admin.view.widget_generator.child_links:
        class:  %darvin_admin.view.widget_generator.child_links.class%
        parent: darvin_admin.view.widget_generator.abstract
        calls:
            - [ setEntityManager,      [ "@doctrine.orm.entity_manager" ] ]
            - [ setIdentifierAccessor, [ "@darvin_admin.metadata.identifier_accessor" ] ]
        tags:
            - { name: darvin_admin.view.widget_generator }

    darvin_admin.view.widget_generator.delete_form:
        class:  %darvin_admin.view.widget_generator.delete_form.class%
        parent: darvin_admin.view.widget_generator.abstract
        calls:
            - [ setAdminFormFactory, [ "@darvin_admin.form.factory" ] ]
        tags:
            - { name: darvin_admin.view.widget_generator }

    darvin_admin.view.widget_generator.edit_link:
        class:  %darvin_admin.view.widget_generator.edit_link.class%
        parent: darvin_admin.view.widget_generator.abstract
        tags:
            - { name: darvin_admin.view.widget_generator }

    darvin_admin.view.widget_generator.email_link:
        class:  %darvin_admin.view.widget_generator.email_link.class%
        parent: darvin_admin.view.widget_generator.abstract
        calls:
            - [ setPropertyAccessor, [ "@property_accessor" ] ]
        tags:
            - { name: darvin_admin.view.widget_generator }

    darvin_admin.view.widget_generator.image_link:
        class:  %darvin_admin.view.widget_generator.image_link.class%
        parent: darvin_admin.view.widget_generator.abstract
        calls:
            - [ setImageUrlBuilder, [ "@darvin_image.url_builder.builder" ] ]
        tags:
            - { name: darvin_admin.view.widget_generator }

    darvin_admin.view.widget_generator.list:
        class:  %darvin_admin.view.widget_generator.list.class%
        parent: darvin_admin.view.widget_generator.abstract
        calls:
            - [ setPropertyAccessor, [ "@property_accessor" ] ]
        tags:
            - { name: darvin_admin.view.widget_generator }

    darvin_admin.view.widget_generator.show_link:
        class:  %darvin_admin.view.widget_generator.show_link.class%
        parent: darvin_admin.view.widget_generator.abstract
        tags:
            - { name: darvin_admin.view.widget_generator }

    darvin_admin.view.widget_generator.pool:
        class: %darvin_admin.view.widget_generator.pool.class%

    darvin_admin.view.widget_generator.pool_provider:
        class: %darvin_admin.view.widget_generator.pool_provider.class%
        arguments:
            - "@service_container"

    darvin_admin.view.widget_generator.twig_extension:
        class:  %darvin_admin.view.widget_generator.twig_extension.class%
        public: false
        arguments:
            - "@darvin_admin.view.widget_generator.pool_provider"
        tags:
            - { name: twig.extension }
