parameters:
    darvin_admin.view.factory.abstract.class: Darvin\AdminBundle\View\Factory\AbstractViewFactory

    darvin_admin.view.factory.index.class: Darvin\AdminBundle\View\Factory\Index\IndexViewFactory

    darvin_admin.view.factory.show.class: Darvin\AdminBundle\View\Factory\Show\ShowViewFactory

    darvin_admin.view.widget.abstract.class: Darvin\AdminBundle\View\Widget\Widget\AbstractWidget
    darvin_admin.view.widget.actions.class: Darvin\AdminBundle\View\Widget\Widget\ActionsWidget
    darvin_admin.view.widget.batch_delete.class: Darvin\AdminBundle\View\Widget\Widget\BatchDeleteWidget
    darvin_admin.view.widget.child_links.class: Darvin\AdminBundle\View\Widget\Widget\ChildLinksWidget
    darvin_admin.view.widget.compound_list.class: Darvin\AdminBundle\View\Widget\Widget\CompoundListWidget
    darvin_admin.view.widget.copy_form.class: Darvin\AdminBundle\View\Widget\Widget\CopyFormWidget
    darvin_admin.view.widget.delete_form.class: Darvin\AdminBundle\View\Widget\Widget\DeleteFormWidget
    darvin_admin.view.widget.edit_link.class: Darvin\AdminBundle\View\Widget\Widget\EditLinkWidget
    darvin_admin.view.widget.email_link.class: Darvin\AdminBundle\View\Widget\Widget\EmailLinkWidget
    darvin_admin.view.widget.empty_widget.class: Darvin\AdminBundle\View\Widget\Widget\EmptyWidget
    darvin_admin.view.widget.entity_list.class: Darvin\AdminBundle\View\Widget\Widget\EntityListWidget
    darvin_admin.view.widget.file_upload_link.class: Darvin\AdminBundle\View\Widget\Widget\FileUploadLinkWidget
    darvin_admin.view.widget.image_link.class: Darvin\AdminBundle\View\Widget\Widget\ImageLinkWidget
    darvin_admin.view.widget.image_upload_link.class: Darvin\AdminBundle\View\Widget\Widget\ImageUploadLinkWidget
    darvin_admin.view.widget.log_entry.data.class: Darvin\AdminBundle\View\Widget\Widget\LogEntry\DataWidget
    darvin_admin.view.widget.log_entry.entity_name.class: Darvin\AdminBundle\View\Widget\Widget\LogEntry\EntityNameWidget
    darvin_admin.view.widget.photo_gallery.class: Darvin\AdminBundle\View\Widget\Widget\PhotoGalleryWidget
    darvin_admin.view.widget.public_link.class: Darvin\AdminBundle\View\Widget\Widget\PublicLinkWidget
    darvin_admin.view.widget.readable_enum.class: Darvin\AdminBundle\View\Widget\Widget\ReadableEnumWidget
    darvin_admin.view.widget.show_link.class: Darvin\AdminBundle\View\Widget\Widget\ShowLinkWidget
    darvin_admin.view.widget.simple_link.class: Darvin\AdminBundle\View\Widget\Widget\SimpleLinkWidget
    darvin_admin.view.widget.simple_list.class: Darvin\AdminBundle\View\Widget\Widget\SimpleListWidget
    darvin_admin.view.widget.switch_user.class: Darvin\AdminBundle\View\Widget\Widget\SwitchUserWidget

    darvin_admin.view.widget.pool.class: Darvin\AdminBundle\View\Widget\WidgetPool

    darvin_admin.view.widget.twig_extension.class: Darvin\AdminBundle\Twig\Extension\ViewWidgetExtension

services:
    _defaults:
        public: true

    darvin_admin.view.factory.abstract:
        class:    '%darvin_admin.view.factory.abstract.class%'
        abstract: true
        calls:
            - [ setContainer,             [ '@service_container' ] ]
            - [ setFieldBlacklistManager, [ '@darvin_admin.metadata.field_blacklist_manager' ] ]
            - [ setPropertyAccessor,      [ '@property_accessor' ] ]
            - [ setStringifier,           [ '@darvin_utils.stringifier.doctrine' ] ]
            - [ setWidgetPool,            [ '@darvin_admin.view.widget.pool' ] ]

    darvin_admin.view.factory.index:
        class:  '%darvin_admin.view.factory.index.class%'
        parent: darvin_admin.view.factory.abstract
        public: true
        arguments:
            - '@darvin_admin.form.factory'
            - '@darvin_admin.form.renderer.property'

    darvin_admin.view.factory.show:
        class:  '%darvin_admin.view.factory.show.class%'
        parent: darvin_admin.view.factory.abstract
        public: true

    darvin_admin.view.widget.abstract:
        class:    '%darvin_admin.view.widget.abstract.class%'
        abstract: true
        public:   false
        calls:
            - [ setAuthorizationChecker, [ '@security.authorization_checker' ] ]
            - [ setMetadataManager,      [ '@darvin_admin.metadata.manager' ] ]
            - [ setPropertyAccessor,     [ '@property_accessor' ] ]
            - [ setTemplating,           [ '@templating' ] ]

    darvin_admin.view.widget.actions:
        class:  '%darvin_admin.view.widget.actions.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        arguments:
            - '@darvin_admin.view.widget.pool'
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.batch_delete:
        class:  '%darvin_admin.view.widget.batch_delete.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        arguments:
            - '@darvin_admin.router'
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.child_links:
        class:  '%darvin_admin.view.widget.child_links.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        calls:
            - [ setAdminRouter,        [ '@darvin_admin.router' ] ]
            - [ setEntityManager,      [ '@doctrine.orm.entity_manager' ] ]
            - [ setEntityResolver,     [ '@darvin_utils.orm.entity_resolver' ] ]
            - [ setIdentifierAccessor, [ '@darvin_admin.metadata.identifier_accessor' ] ]
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.compound_list:
        class:  '%darvin_admin.view.widget.compound_list.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.copy_form:
        class:  '%darvin_admin.view.widget.copy_form.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        calls:
            - [ setAdminFormFactory,        [ '@darvin_admin.form.factory' ] ]
            - [ setAdminRouter,             [ '@darvin_admin.router' ] ]
            - [ setExtendedMetadataFactory, [ '@darvin_utils.mapping.metadata_factory' ] ]
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.delete_form:
        class:  '%darvin_admin.view.widget.delete_form.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        calls:
            - [ setAdminFormFactory, [ '@darvin_admin.form.factory' ] ]
            - [ setAdminRouter,      [ '@darvin_admin.router' ] ]
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.edit_link:
        class:  '%darvin_admin.view.widget.edit_link.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        calls:
            - [ setAdminRouter, [ '@darvin_admin.router' ] ]
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.email_link:
        class:  '%darvin_admin.view.widget.email_link.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.empty_widget:
        class:  '%darvin_admin.view.widget.empty_widget.class%'
        public: false
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.entity_list:
        class:  '%darvin_admin.view.widget.entity_list.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        calls:
            - [ setWidgetPool, [ '@darvin_admin.view.widget.pool' ] ]
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.file_upload_link:
        class:  '%darvin_admin.view.widget.file_upload_link.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        calls:
            - [ setUploadStorage, [ '@vich_uploader.storage' ] ]
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.image_link:
        class:  '%darvin_admin.view.widget.image_link.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        calls:
            - [ setImageUrlBuilder, [ '@darvin_image.url_builder.builder' ] ]
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.image_upload_link:
        class:  '%darvin_admin.view.widget.image_upload_link.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        calls:
            - [ setUploadStorage, [ '@vich_uploader.storage' ] ]
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.log_entry.data:
        class:  '%darvin_admin.view.widget.log_entry.data.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@darvin_utils.object_namer'
            - '@darvin_utils.stringifier.doctrine'
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.log_entry.entity_name:
        class:  '%darvin_admin.view.widget.log_entry.entity_name.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        arguments:
            - '@darvin_utils.object_namer'
            - '@darvin_content.translatable.manager'
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.photo_gallery:
        class:  '%darvin_admin.view.widget.photo_gallery.class%'
        parent: darvin_admin.view.widget.entity_list
        public: false
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.public_link:
        class:  '%darvin_admin.view.widget.public_link.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        calls:
            - [ setHomepageRouter, [ '@darvin_utils.homepage.router' ] ]
            - [ setRouter,         [ '@router' ] ]
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.readable_enum:
        class:  '%darvin_admin.view.widget.readable_enum.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.show_link:
        class:  '%darvin_admin.view.widget.show_link.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        calls:
            - [ setAdminRouter, [ '@darvin_admin.router' ] ]
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.simple_link:
        class:  '%darvin_admin.view.widget.simple_link.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.simple_list:
        class:  '%darvin_admin.view.widget.simple_list.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.switch_user:
        class:  '%darvin_admin.view.widget.switch_user.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        tags:
            - { name: darvin_admin.view_widget }

    darvin_admin.view.widget.pool:
        class: '%darvin_admin.view.widget.pool.class%'
        tags:
            - { name: darvin_utils.providable }

    darvin_admin.view.widget.twig_extension:
        class:  '%darvin_admin.view.widget.twig_extension.class%'
        public: false
        arguments:
            - '@darvin_admin.view.widget.pool.provider'
        tags:
            - { name: twig.extension }
