parameters:
    darvin_admin.cache.cleaner.class:                 Darvin\AdminBundle\Cache\CacheCleaner
    darvin_admin.cache.controller.widget_clear.class: Darvin\AdminBundle\Controller\Cache\WidgetClearController
    darvin_admin.cache.controller.clear.class:        Darvin\AdminBundle\Controller\Cache\ClearController
    darvin_admin.cache.form_factory.class:            Darvin\AdminBundle\Form\Factory\Cache\CacheFormFactory
    darvin_admin.cache.form_renderer.class:           Darvin\AdminBundle\Form\Renderer\Cache\CacheFormRenderer
    darvin_admin.cache.twig_extension.class:          Darvin\AdminBundle\Twig\Extension\CacheExtension

services:
    darvin_admin.cache.controller.clear:
        class: '%darvin_admin.cache.controller.clear.class%'
        arguments:
            - '@darvin_admin.cache.cleaner'
            - '@darvin_admin.cache.form_factory'
            - '@darvin_admin.cache.form_renderer'
            - '@darvin_utils.flash.notifier'
            - '@router'
            - '@twig'
        tags:
            - { name: controller.service_arguments }

    darvin_admin.cache.controller.widget_clear:
        class: '%darvin_admin.cache.controller.widget_clear.class%'
        arguments:
            - '@darvin_admin.cache.cleaner'
            - '@darvin_admin.cache.form_factory'
            - '@darvin_admin.cache.form_renderer'
            - '@darvin_utils.flash.notifier'
            - '@router'
        tags:
            - { name: controller.service_arguments }

    darvin_admin.cache.cleaner:
        class: '%darvin_admin.cache.cleaner.class%'
        arguments:
            - '@logger'

    darvin_admin.cache.form_factory:
        class: '%darvin_admin.cache.form_factory.class%'
        arguments:
            - '@darvin_admin.cache.cleaner'
            - '@form.factory'
            - '@router'

    darvin_admin.cache.form_renderer:
        class: '%darvin_admin.cache.form_renderer.class%'
        arguments:
            - '@darvin_admin.cache.cleaner'
            - '@darvin_admin.cache.form_factory'
            - '@router'
            - '@twig'

    darvin_admin.cache.twig_extension:
        class:  '%darvin_admin.cache.twig_extension.class%'
        public: false
        arguments:
            - '@darvin_admin.cache.form_renderer'
        tags:
            - { name: twig.extension }
