parameters:
    darvin_admin.cache.cleaner.class: Darvin\AdminBundle\Cache\CacheCleaner

services:
    darvin_admin.cache.cleaner:
        class: '%darvin_admin.cache.cleaner.class%'
        arguments:
            - '@kernel'
        calls:
            - [ setLogger, [ '@?logger' ] ]
