parameters:
    darvin_admin.ckeditor.controller.plugin.class: Darvin\AdminBundle\Controller\CKEditor\PluginController

    darvin_admin.ckeditor.form_type.common.class: Darvin\AdminBundle\Form\Type\CKEditorType

    darvin_admin.ckeditor.form_type.compact.class: Darvin\AdminBundle\Form\Type\CKEditorCompactType

services:
    darvin_admin.ckeditor.controller.plugin:
        class: '%darvin_admin.ckeditor.controller.plugin.class%'
        arguments:
            - '@translator'
            - '@twig'
            - '@darvin_content.widget.pool'
            - '%kernel.debug%'
        tags:
            - { name: controller.service_arguments }

    darvin_admin.ckeditor.form_type.common:
        class: '%darvin_admin.ckeditor.form_type.common.class%'
        arguments:
            - '@assets.packages'
            - '@darvin_utils.locale.provider'
            - '@property_accessor'
            - '@router'
            - '@darvin_content.translatable.manager'
            - '@darvin_content.widget.pool'
            - '%darvin_admin.ckeditor.apply_contents_css%'
            - '@=parameter("kernel.debug") ? "assets/build-dev" : "assets/build"'
            - '%darvin_admin.ckeditor.plugin_filename%'
            - '%darvin_admin.ckeditor.plugins_path%'
        tags:
            - { name: form.type }

    darvin_admin.ckeditor.form_type.compact:
        class: '%darvin_admin.ckeditor.form_type.compact.class%'
        arguments:
            - '@darvin_utils.locale.provider'
        tags:
            - { name: form.type }
