parameters:
    darvin_admin.configuration.controller.edit.class: Darvin\AdminBundle\Controller\Configuration\EditController

    darvin_admin.configuration.form_type.configurations.class: Darvin\AdminBundle\Form\Type\Configuration\ConfigurationsType

    darvin_admin.configuration.section.class: Darvin\AdminBundle\Configuration\SectionConfiguration

services:
    darvin_admin.configuration.controller.edit:
        class: '%darvin_admin.configuration.controller.edit.class%'
        arguments:
            - '@darvin_config.configuration.pool'
            - '@darvin_utils.flash.notifier'
            - '@form.factory'
            - '@router'
            - '@twig'
        calls:
            - [ setCacheClearer, [ '@?darvin_admin.cache.clear.clearer' ] ]
        tags:
            - { name: controller.service_arguments }

    darvin_admin.configuration.form_type.configurations:
        class: '%darvin_admin.configuration.form_type.configurations.class%'
        arguments:
            - '@darvin_utils.security.accessibility_checker'
            - '@darvin_config.configuration.pool'
        tags:
            - { name: form.type }

    darvin_admin.configuration.section:
        class:  '%darvin_admin.configuration.section.class%'
        public: true
        arguments:
            - '@darvin_utils.orm.entity_resolver'
            - '@darvin_utils.object_namer'
            - '%darvin_admin.sections%'
