parameters:
    darvin_admin.dropzone.form_type.class: Darvin\AdminBundle\Form\Type\Dropzone\DropzoneType

services:
    darvin_admin.dropzone.form_type:
        class: '%darvin_admin.dropzone.form_type.class%'
        arguments:
            - '@darvin_utils.orm.entity_resolver'
            - '@oneup_uploader.templating.uploader_helper'
            - '@property_accessor'
            - '@translator'
            - '@vich_uploader.metadata_reader'
            - '@=container.hasParameter("darvin_file.constraints") ? parameter("darvin_file.constraints") : []'
            - '%darvin_admin.upload_max_size_mb%'
            - '%darvin_image.constraints%'
            - '%darvin_image.upload_max_size_mb%'
            - '%oneup_uploader.config%'
            - '@darvin_image.size.describer'
        tags:
            - { name: form.type }
