parameters:
    darvin_admin.error.show_error_page_subscriber.class:          Darvin\AdminBundle\EventListener\ShowErrorPageSubscriber
    darvin_admin.error.show_error_page_subscriber.homepage_route: darvin_admin_homepage

services:
    darvin_admin.error.show_error_page_subscriber:
        class: '%darvin_admin.error.show_error_page_subscriber.class%'
        arguments:
            - '@security.authorization_checker'
            - '@logger'
            - '@router'
            - '@twig'
            - '@translator'
            - '%darvin_admin.error.show_error_page_subscriber.homepage_route%'
            - '%darvin_admin.locales%'
            - '%darvin_admin.default_locale%'
        tags:
            - { name: kernel.event_subscriber }
