parameters:
    darvin_admin.locale.form_type.class: Darvin\AdminBundle\Form\Type\LocaleType

services:
    darvin_admin.locale.form_type:
        class: '%darvin_admin.locale.form_type.class%'
        arguments:
            - '%darvin_admin.locales%'
        tags:
            - { name: form.type }
