parameters:
    darvin_admin.menu.class: Darvin\AdminBundle\Menu\Menu

    darvin_admin.menu.item_factory.cache.class: Darvin\AdminBundle\Menu\Item\Factory\CacheItemFactory

    darvin_admin.menu.item_factory.configuration.class: Darvin\AdminBundle\Menu\Item\Factory\ConfigurationItemFactory

    darvin_admin.menu.item_factory.group.class: Darvin\AdminBundle\Menu\Item\Factory\GroupItemFactory

    darvin_admin.menu.item_factory.section.class: Darvin\AdminBundle\Menu\Item\Factory\SectionItemFactory

    darvin_admin.menu.item_factory.separator.class: Darvin\AdminBundle\Menu\Item\Factory\SeparatorItemFactory

    darvin_admin.menu.twig_extension.class: Darvin\AdminBundle\Twig\Extension\MenuExtension

services:
    darvin_admin.menu:
        class: '%darvin_admin.menu.class%'
        arguments:
            - '@darvin_utils.new_object.counter'
            - '@request_stack'

    darvin_admin.menu.item_factory.cache:
        class: '%darvin_admin.menu.item_factory.cache.class%'
        arguments:
            - '@security.authorization_checker'
            - '@router'
            - "%darvin_admin.cache.list%"
        tags:
            - { name: darvin_admin.menu_item_factory }

    darvin_admin.menu.item_factory.configuration:
        class: '%darvin_admin.menu.item_factory.configuration.class%'
        arguments:
            - '@security.authorization_checker'
            - '@router'
        tags:
            - { name: darvin_admin.menu_item_factory }

    darvin_admin.menu.item_factory.group:
        class: '%darvin_admin.menu.item_factory.group.class%'
        arguments:
            - '%darvin_admin.menu.groups%'
        tags:
            - { name: darvin_admin.menu_item_factory }

    darvin_admin.menu.item_factory.section:
        class: '%darvin_admin.menu.item_factory.section.class%'
        arguments:
            - '@darvin_admin.router'
            - '@security.authorization_checker'
            - '@doctrine.orm.entity_manager'
            - '@darvin_admin.metadata.manager'
        tags:
            - { name: darvin_admin.menu_item_factory }

    darvin_admin.menu.item_factory.separator:
        class: '%darvin_admin.menu.item_factory.separator.class%'
        arguments:
            - '%darvin_admin.menu.groups%'
        tags:
            - { name: darvin_admin.menu_item_factory }

    darvin_admin.menu.twig_extension:
        class: '%darvin_admin.menu.twig_extension.class%'
        arguments:
            - '@darvin_admin.menu'
        tags:
            - { name: twig.extension }
