parameters:
    darvin_admin.pagination.form.factory.class: Darvin\AdminBundle\Form\Factory\PaginationFormFactory

    darvin_admin.pagination.form.renderer.class: Darvin\AdminBundle\Form\Renderer\PaginationFormRenderer

    darvin_admin.pagination.form.twig.extension.class: Darvin\AdminBundle\Twig\Extension\Pagination\FormExtension

    darvin_admin.pagination.manager.class: Darvin\AdminBundle\Pagination\PaginationManager

    darvin_admin.pagination.repaginate.form.type.class: Darvin\AdminBundle\Form\Type\Pagination\RepaginateType

services:
    darvin_admin.pagination.form.factory:
        class: '%darvin_admin.pagination.form.factory.class%'
        arguments:
            - '@darvin_admin.router'
            - '@form.factory'
            - '@darvin_admin.pagination.manager'

    darvin_admin.pagination.form.renderer:
        class: '%darvin_admin.pagination.form.renderer.class%'
        arguments:
            - '@darvin_admin.pagination.form.factory'
            - '@twig'

    darvin_admin.pagination.form.twig.extension:
        class: '%darvin_admin.pagination.form.twig.extension.class%'
        arguments:
            - '@darvin_admin.pagination.form.renderer'
        tags:
            - { name: twig.extension }

    darvin_admin.pagination.manager:
        class: '%darvin_admin.pagination.manager.class%'
        arguments:
            - '@darvin_utils.orm.entity_resolver'
            - '@darvin_admin.metadata.manager'
            - '@session'

    darvin_admin.pagination.repaginate.form.type:
        class: '%darvin_admin.pagination.repaginate.form.type.class%'
        arguments:
            - '@darvin_admin.metadata.manager'
        tags:
            - { name: form.type }
