parameters:
    darvin_admin.toolbar.renderer.class: Darvin\AdminBundle\Toolbar\ToolbarRenderer

    darvin_admin.toolbar.twig_extension.class: Darvin\AdminBundle\Twig\Extension\ToolbarExtension

services:
    darvin_admin.toolbar.renderer:
        class: '%darvin_admin.toolbar.renderer.class%'

    darvin_admin.toolbar.twig_extension:
        class: '%darvin_admin.toolbar.twig_extension.class%'
        arguments:
            - '@darvin_admin.toolbar.renderer'
        tags:
            - { name: twig.extension }
