parameters:
    darvin_admin.translation.clear_cache_subscriber.class: Darvin\AdminBundle\EventListener\ClearTranslationCacheSubscriber

services:
    darvin_admin.translation.clear_cache_subscriber:
        class: '%darvin_admin.translation.clear_cache_subscriber.class%'
        arguments:
            - '@service_container'
        tags:
            - { name: doctrine.event_subscriber }
