parameters:
    darvin_admin.twig.globals.class: Darvin\AdminBundle\Twig\Globals

services:
    darvin_admin.twig.globals:
        class: '%darvin_admin.twig.globals.class%'
        arguments:
            - '%darvin_admin.frontend_path%'
            - '%darvin_admin.locales%'
            - '%darvin_admin.logo%'
            - '%darvin_admin.project_title%'
            - '%darvin_admin.assets.scripts%'
            - '%darvin_admin.assets.styles%'
            - '%darvin_admin.support.chat.id%'
            - '%darvin_admin.yandex.metrika.id%'
