entity_name: image
disabled_routes:
    - copy
    - delete
    - new
    - show
images:
    homepage_menu_icon: bundles/darvinadmin/images/icons/homepage/image.png
menu:
    color:    "#0a9771"
    position: 30
form:
    edit:
        type: Darvin\ImageBundle\Form\Type\Image\Image\SizesType
    filter:
        fields:
            name:
                compare_strict: false
            extension:
                compare_strict: false
    index:
        fields:
            name: ~
view:
    edit:
        action_widgets: ~
    index:
        action_widgets:
            edit_link:
                entity_class: Darvin\ImageBundle\Entity\Image\AbstractImage
        fields:
            image:
                widget:
                    alias: image_link
            name:      ~
            extension: ~
