entity_name: image
disabled_routes:
    - delete
    - new
    - show
images:
    homepage_menu_icon: bundles/darvinadmin/images/icons/homepage/image.png
menu:
    color:    "#0a9771"
    position: 30
form:
    edit:
        type: Darvin\ImageBundle\Form\Type\Image\Image\SizesType
    filter:
        fields:
            name:
                strict_comparison: false
            extension:
                strict_comparison: false
    index:
        fields:
            name: ~
view:
    edit:
        action_widgets: {}
    index:
        action_widgets:
            - edit_link
        fields:
            image:
                widget_generator:
                    alias: image_link
                    options:
                        filter_parameters:
                            size_name: darvin_admin
                            outbound:  true
            name:      ~
            extension: ~
