darvin_admin:
    entity_name: image
    disabled_routes:
        - delete
        - new
        - show
    form:
        edit:
            type: darvin_image_image_sizes
        index:
            fields:
                name: ~
    view:
        edit:
            action_widgets: {}
        index:
            action_widgets:
                - edit_link
            fields:
                image:
                    widget_generator:
                        alias: image_link
                        options:
                            filter_parameters:
                                size_name: darvin_admin
                                outbound:  true
                name:      ~
                extension: ~
