entity_name: log
menu:
    color: "#cf3cc5"
disabled_routes:
    - copy
    - delete
    - edit
    - new
    - update-property
sortable_fields:
    actionName: action
    loggedAt:   ~
    objectName: objectClass
    objectId:   ~
    version:    ~
    username:   ~
form:
    filter:
        fields:
            action:
                type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
                options:
                    choices: [ Darvin\AdminBundle\Entity\LogEntry, getActions ]
            loggedAtFrom: ~
            loggedAtTo:   ~
            objectClass:
                compare_strict: false
            version:
                compare_strict: false
            username:
                compare_strict: false
view:
    index:
        action_widgets:
            - show_link
            - log_entry_revert_form
        fields:
            actionName: ~
            loggedAt:   ~
            objectName:
                widget:
                    alias: log_entry_entity_name
            objectId: ~
            object:
                widget:
                    alias: show_link
                    options:
                        property: object
            version:  ~
            username: ~
            user:
                widget:
                    alias: show_link
                    options:
                        property: user
    show:
        action_widgets:
            - log_entry_revert_form
        fields:
            actionName: ~
            loggedAt:   ~
            objectName:
                widget:
                    alias: log_entry_entity_name
            objectId: ~
            object:
                widget:
                    alias: show_link
                    options:
                        property: object
            version:  ~
            username: ~
            user:
                widget:
                    alias: show_link
                    options:
                        property: user
            data:
                widget:
                    alias: log_entry_data
