menu:
    group: modules
    icons:
        main: bundles/darvinadmin/images/admin/log_main.png
route_blacklist:
    - batch-delete
    - copy
    - delete
    - edit
    - new
    - update-property
sortable_fields:
    actionName: action
    loggedAt:   ~
    objectName: objectClass
    objectId:   ~
    version:    ~
    username:   ~
form:
    filter:
        fields:
            action:
                type: choice
                options:
                    choices: [ Darvin\AdminBundle\Entity\LogEntry, getActionChoices ]
            loggedAtFrom: ~
            loggedAtTo:   ~
            objectClass:
                compare_strict: false
            version:
                compare_strict: false
            username:
                compare_strict: false
view:
    index:
        action_widgets:
            show_link: ~
        fields:
            actionName: ~
            loggedAt:   ~
            objectName:
                widget: log_entry_entity_name
            objectId: ~
            object:
                widget: show_link
            version:  ~
            username: ~
            user:
                widget: show_link
    show:
        fields:
            actionName: ~
            loggedAt:   ~
            objectName:
                widget: log_entry_entity_name
            objectId: ~
            object:
                widget: show_link
            version:  ~
            username: ~
            user:
                widget: show_link
            data:
                widget: log_entry_data
