Darvin\AdminBundle\Entity\LogEntry:
    disabled_routes:
        - copy
        - delete
        - edit
        - new
        - update-property
    entity_name: log
    view:
        index:
            action_widgets:
                - show_link
            fields:
                actionName: ~
                loggedAt:   ~
                objectName:
                    widget_generator:
                        alias: log_entry_entity_name
                objectId: ~
                version:  ~
                username: ~
        show:
            action_widgets: ~
            fields:
                actionName: ~
                loggedAt:   ~
                objectName:
                    widget_generator:
                        alias: log_entry_entity_name
                objectId: ~
                version:  ~
                username: ~
                data:
                    widget_generator:
                        alias: log_entry_data
