Darvin\AdminBundle\Entity\LogEntry:
    disabled_routes:
        - copy
        - delete
        - edit
        - new
        - update-property
    entity_name: log
    view:
        index:
            action_widgets:
                - show_link
                - log_entry_revert_form
            fields:
                actionName: ~
                loggedAt:   ~
                objectName:
                    widget_generator:
                        alias: log_entry_entity_name
                objectId: ~
                object:
                    widget_generator:
                        alias: show_link
                        options:
                            entity_property: object
                version:  ~
                username: ~
                administrator:
                    widget_generator:
                        alias: show_link
                        options:
                            entity_property: administrator
        show:
            action_widgets:
                - log_entry_revert_form
            fields:
                actionName: ~
                loggedAt:   ~
                objectName:
                    widget_generator:
                        alias: log_entry_entity_name
                objectId: ~
                object:
                    widget_generator:
                        alias: show_link
                        options:
                            entity_property: object
                version:  ~
                username: ~
                administrator:
                    widget_generator:
                        alias: show_link
                        options:
                            entity_property: administrator
                data:
                    widget_generator:
                        alias: log_entry_data
