Darvin\AdminBundle\Entity\LogEntry:
    disabled_routes:
        - copy
        - delete
        - edit
        - new
        - update-property
    entity_name: log
    view:
        index:
            action_widgets:
                - show_link
            fields:
                actionTranslation: ~
                loggedAt:          ~
                objectClass:       ~
                objectId:          ~
                version:           ~
                username:          ~
        show:
            action_widgets: ~
            fields:
                actionTranslation: ~
                loggedAt:          ~
                objectClass:       ~
                objectId:          ~
                version:           ~
                username:          ~
                data:              ~
