Darvin\AdminBundle\Entity\LogEntry:
    disabled_routes:
        - copy
        - delete
        - edit
        - new
        - update-property
    view:
        index:
            action_widgets:
                - show_link
            fields:
                action:      ~
                loggedAt:    ~
                objectClass: ~
                objectId:    ~
                version:     ~
                username:    ~
        show:
            action_widgets: ~
            fields:
                action:      ~
                loggedAt:    ~
                objectClass: ~
                objectId:    ~
                version:     ~
                username:    ~
                data:        ~
