menu:
    group:    modules
    position: 10
    icons:
        main: bundles/darvinadmin/images/admin/translation_main.png
route_blacklist:
    - batch-delete
    - copy
    - delete
    - edit
    - new
    - show
view:
    index:
        action_widgets: ~
        fields:
            content:          ~
            locale:           ~
            transUnit.domain: ~
            updatedAt:        ~
form:
    index:
        fields:
            content:
                type: text
    filter:
        fields:
            content:
                compare_strict: false
            locale:
                compare_strict: false
            updatedAtFrom: ~
            updatedAtTo:   ~
