assetic:
    debug: %kernel.debug%
    java:  /usr/bin/java
    filters:
        closure:
            jar: %kernel.root_dir%/../vendor/darvinstudio/darvin-admin-bundle/Resources/java/compiler.jar
        cssembed:
            jar: %kernel.root_dir%/../vendor/darvinstudio/darvin-admin-bundle/Resources/java/cssembed-0.4.5.jar
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/../vendor/darvinstudio/darvin-admin-bundle/Resources/java/yuicompressor-2.4.8.jar
