fm_elfinder:
    assets_path: /assets/components
    instances:
        default:
            editor: ckeditor
            connector:
                debug: "%kernel.debug%"
                roots:
                    uploads:
                        driver:          LocalFileSystem
                        path:            "%upload_path%"
                        upload_max_size: "%upload_max_size_mb%M"
                        upload_allow:
                            - image/png
                            - image/jpg
                            - image/jpeg
                            # MSO
                            - application/vnd.ms-office
                            # *.doc
                            - application/msword
                            # *.docx
                            - application/vnd.openxmlformats-officedocument.wordprocessingml.document
                            # *.xls
                            - application/excel
                            - application/vnd.ms-excel
                            - application/x-excel
                            - application/x-msexcel
                            # *.xlsx
                            - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                            # *.pdf
                            - application/pdf
                            # *.zip
                            - application/x-compressed
                            - application/x-zip-compressed
                            - application/zip
                            - multipart/x-zip
        darvin_admin_text:
            editor:          custom
            editor_template: 'DarvinAdminBundle:ElFinder:text.html.twig'
            connector:
                debug: "%kernel.debug%"
                roots:
                    uploads:
                        driver:          LocalFileSystem
                        path:            "%upload_path%"
                        upload_max_size: "%upload_max_size_mb%M"
                        upload_allow:
                            - image/png
                            - image/jpg
                            - image/jpeg
                            # MSO
                            - application/vnd.ms-office
                            # *.doc
                            - application/msword
                            # *.docx
                            - application/vnd.openxmlformats-officedocument.wordprocessingml.document
                            # *.xls
                            - application/excel
                            - application/vnd.ms-excel
                            - application/x-excel
                            - application/x-msexcel
                            # *.xlsx
                            - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                            # *.pdf
                            - application/pdf
                            # *.zip
                            - application/x-compressed
                            - application/x-zip-compressed
                            - application/zip
                            - multipart/x-zip
