fos_ck_editor:
    autoload: false
    jquery:   true
    configs:
        darvin_admin:
            allowedContent:         true
            height:                 300
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters:
                instance: darvin_admin_ckeditor
            toolbar:
                - [ Source ]
                - [ Image, Flash, Table, SpecialChar ]
                - [ NumberedList, BulletedList, -, Outdent, Indent, -, JustifyLeft, JustifyCenter, JustifyRight, JustifyBlock ]
                - [ Link, Unlink, Anchor ]
                - [ Bold, Italic, Underline, Strike, Subscript, Superscript, -, RemoveFormat ]
                - [ Format, Font, FontSize ]
                - [ TextColor, BGColor ]
                - [ Maximize, ShowBlocks ]
                - [ Find, Replace ]
            removePlugins: >
                a11yhelp,
                about,
                bidi,
                blockquote,
                colordialog,
                dialogadvtab,
                div,
                elementspath,
                enterkey,
                entities,
                floatingspace,
                forms,
                horizontalrule,
                iframe,
                indentblock,
                language,
                liststyle,
                magicline,
                newpage,
                pagebreak,
                pastefromword,
                pastetext,
                preview,
                print,
                save,
                scayt,
                selectall,
                showborders,
                smiley,
                stylescombo,
                tab,
                templates,
                wsc
        darvin_admin_compact:
            allowedContent:         true
            height:                 100
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters:
                instance: darvin_admin_ckeditor
            toolbar:
                - [ Source ]
                - [ Image, Flash, Table, SpecialChar ]
                - [ NumberedList, BulletedList, -, Outdent, Indent, -, JustifyLeft, JustifyCenter, JustifyRight, JustifyBlock ]
                - [ Link, Unlink, Anchor ]
                - [ Bold, Italic, Underline, Strike, Subscript, Superscript, -, RemoveFormat ]
                - [ Format, Font, FontSize ]
                - [ TextColor, BGColor ]
                - [ Maximize, ShowBlocks ]
                - [ Find, Replace ]
            removePlugins: >
                a11yhelp,
                about,
                bidi,
                blockquote,
                colordialog,
                dialogadvtab,
                div,
                elementspath,
                enterkey,
                entities,
                floatingspace,
                forms,
                horizontalrule,
                iframe,
                indentblock,
                language,
                liststyle,
                magicline,
                newpage,
                pagebreak,
                pastefromword,
                pastetext,
                preview,
                print,
                save,
                scayt,
                selectall,
                showborders,
                smiley,
                stylescombo,
                tab,
                templates,
                wsc
