fos_ck_editor:
    autoload: false
    jquery:   true
    configs:
        darvin_admin:
            allowedContent:                   true
            filebrowserBrowseRoute:           elfinder
            filebrowserBrowseRouteParameters: []
            height:                           300
            toolbar:
                - [ Source ]
                - [ Image, Flash, Table, SpecialChar ]
                - [ NumberedList, BulletedList, -, Outdent, Indent, -, JustifyLeft, JustifyCenter, JustifyRight, JustifyBlock ]
                - [ Link, Unlink, Anchor ]
                - [ Bold, Italic, Underline, Strike, Subscript, Superscript, -, RemoveFormat ]
                - [ Format, Font, FontSize ]
                - [ TextColor, BGColor ]
                - [ Maximize, ShowBlocks ]
                - [ Find, Replace ]
            removePlugins: >
                a11yhelp,
                about,
                bidi,
                blockquote,
                colordialog,
                dialogadvtab,
                div,
                elementspath,
                enterkey,
                entities,
                floatingspace,
                forms,
                horizontalrule,
                iframe,
                indentblock,
                language,
                liststyle,
                magicline,
                newpage,
                pagebreak,
                pastefromword,
                pastetext,
                preview,
                print,
                save,
                scayt,
                selectall,
                showborders,
                smiley,
                stylescombo,
                tab,
                templates,
                wsc
        darvin_admin_compact:
            allowedContent:                   true
            filebrowserBrowseRoute:           elfinder
            filebrowserBrowseRouteParameters: []
            height:                           100
            toolbar:
                - [ Source ]
                - [ Image ]
                - [ Bold, Italic, Underline, Strike, Subscript, Superscript, -, RemoveFormat ]
            removePlugins: >
                a11yhelp,
                about,
                bidi,
                blockquote,
                colorbutton,
                colordialog,
                dialogadvtab,
                div,
                elementspath,
                enterkey,
                entities,
                find,
                flash,
                floatingspace,
                font,
                format,
                forms,
                horizontalrule,
                iframe,
                indentblock,
                indentlist,
                justify,
                language,
                link,
                list,
                liststyle,
                magicline,
                maximize,
                newpage,
                pagebreak,
                pastefromword,
                pastetext,
                preview,
                print,
                save,
                scayt,
                selectall,
                showblocks,
                showborders,
                smiley,
                specialchar,
                stylescombo,
                tab,
                templates,
                wsc
