hwi_oauth:
    firewall_names:
        - admin_area
    resource_owners:
        darvin_auth_admin:
            type:                oauth2
            client_id:           "%darvin_auth_client_id%"
            client_secret:       "%darvin_auth_client_secret%"
            access_token_url:    https://auth.darvins.ru/oauth/v2/token
            authorization_url:   https://auth.darvins.ru/oauth/v2/auth
            infos_url:           https://auth.darvins.ru/api/user
            user_response_class: Darvin\UserBundle\Security\OAuth\Response\DarvinAuthResponse
            options:
                csrf: true
            paths:
                identifier:     username
                nickname:       username
                realname:       fullname

                error:          error
                phone:          phone
                profilepicture: picture
                roles:          roles
