security:
    encoders:
        Darvin\AdminBundle\Entity\Administrator:
            algorithm:      pbkdf2
            hash_algorithm: sha512

    providers:
        administrator:
            id: darvin_admin.security.user_provider.administrator
        hwi:
            id: darvin_admin.security.user_provider.oauth_administrator

    firewalls:
        admin_area:
            pattern:  ^/admin/
            provider: administrator
            form_login:
                check_path:          darvin_admin_security_login_check
                login_path:          darvin_admin_security_login
                default_target_path: darvin_admin_homepage
                use_referer:         true
                intention:           %secret%
                csrf_provider:       security.csrf.token_manager
                remember_me:         true
            remember_me:
                key:      %secret%
                name:     REMEMBERMEADMIN
                lifetime: 31536000 # 1 year
            logout:
                path:   darvin_admin_security_logout
                target: darvin_admin_security_login
            anonymous: ~
            oauth:
                resource_owners:
                    darvin_auth: darvin_admin_security_login_check_darvin_auth
                login_path:   darvin_admin_security_login
                failure_path: darvin_admin_security_login
                oauth_user_provider:
                    service: darvin_admin.security.user_provider.oauth_administrator
                check_path: darvin_admin_security_login_check_oauth

    access_control:
        - { path: ^/admin/login, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/admin/,      roles: [ IS_AUTHENTICATED_REMEMBERED ] }
