parameters:
    darvin_admin.cache.filesystem.class:     Symfony\Component\Cache\Psr16Cache
    darvin_admin.cache.filesystem.adapter:   Symfony\Component\Cache\Adapter\FilesystemAdapter
    darvin_admin.cache.filesystem.namespace: darvin_admin
    darvin_admin.cache.filesystem.lifetime:  0

services:
    darvin_admin.cache:
        alias: darvin_admin.cache.filesystem

    darvin_admin.cache.filesystem:
        class: '%darvin_admin.cache.filesystem.class%'
        arguments:
            - !service
                class: '%darvin_admin.cache.filesystem.adapter%'
                arguments:
                    - '%darvin_admin.cache.filesystem.namespace%'
                    - '%darvin_admin.cache.filesystem.lifetime%'
                    - '%kernel.cache_dir%'
