darvin_admin_autocomplete:
    path:         /{provider}
    defaults:     { _controller: darvin_content.autocomplete.controller }
    requirements: { provider: '[0-9a-z-]+' }
    methods:      [ get ]
