darvin_admin_cache_widget_clear:
    path:     /clear/widget/
    defaults: { _controller: darvin_admin.cache.controller.clear.widget }
darvin_admin_cache_clear:
    path:     /clear/
    defaults: { _controller: darvin_admin.cache.controller.clear.list }
