darvin_admin_ckeditor_plugin:
    path:         /plugins/{widgetName}.js
    defaults:     { _controller: darvin_admin.ckeditor.controller.plugin }
    requirements: { widgetName: .+ }
    methods:      [ get ]

darvin_admin_ckeditor_plugin_path:
    path: /plugins/
