darvin_admin_search_results:
    path:         /{entityName}/{query}
    defaults:     { _controller: darvin_admin.search.controller.results }
    requirements: { entityName: '[0-9a-z_]+', query: .+ }
    methods:      [ get ]
    condition:    request.isXmlHttpRequest()

darvin_admin_search:
    path:     /
    defaults: { _controller: darvin_admin.search.controller.index }
    methods:  [ get ]
