darvin_admin_security_darvin_auth_login_check:
    path:     /login/darvin-auth/check
    defaults: { _remember_me: on }

darvin_admin_security_login_check:
    path: /login/check

darvin_admin_security_login:
    path:     /login
    defaults: { _controller: DarvinAdminBundle:Security:login }

darvin_admin_security_darvin_auth_login:
    path:     /login/{service}
    defaults: { _controller: HWIOAuthBundle:Connect:redirectToService }

darvin_admin_security_logout:
    path: /logout
